env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:svelte/prettier
  - plugin:import/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/parsers:
    svelte-eslint-parser: [.svelte]
    espree: [.js]
rules:
  no-unused-vars: warn
  import/no-unresolved: off
  import/order:
    - warn
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
