name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm check
      - run: pnpm build
      - run: touch build/.nojekyll
      - if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v4
        with:
          path: build
      - if: github.ref_name == github.event.repository.default_branch
        id: deployment
        uses: actions/deploy-pages@v4
