name: github pages

on:
  push:
    branches: [ v2-gulp ]
  pull_request:
    branches: [ v2-gulp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        
      - name: node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: gulp
        uses: elstudio/actions-js-build/build@v4
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
